version: "3"

services:
  redis:
    image: redis
    restart: always
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD","redis-cli","ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  producer:
    build:
      context: ./producer
      dockerfile:  Dockerfile
    restart: always
    depends_on:
      redis:
        condition: service_healthy
    stdin_open: true
    tty: true

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - redis
      - producer
    tty: true

